-- LazyVim-style behavior using Nix-managed plugins and native Neovim APIs.
local function map(mode, lhs, rhs, desc)
  vim.keymap.set(mode, lhs, rhs, { silent = true, desc = desc })
end

local function root()
  local name = vim.api.nvim_buf_get_name(0)
  local start = name ~= "" and name or vim.fn.getcwd()
  return vim.fs.root(start, {
    ".git",
    "package.json",
    "pyproject.toml",
    "go.mod",
    "mix.exs",
    "build.zig",
    function(name)
      return name:match("%.sln$") ~= nil or name:match("%.csproj$") ~= nil
    end,
  }) or vim.fn.getcwd()
end

local function pick(source, cwd)
  return function()
    Snacks.picker[source]({ cwd = cwd == "root" and root() or nil })
  end
end

map("n", "<leader><space>", pick("files", "root"), "Find Files (Root)")
map("n", "<leader>ff", pick("files", "root"), "Find Files (Root)")
map("n", "<leader>fF", pick("files"), "Find Files (cwd)")
map("n", "<leader>fg", pick("git_files", "root"), "Find Git Files")
map("n", "<leader>fr", pick("recent"), "Recent Files")
map("n", "<leader>fR", pick("recent", "root"), "Recent Files (Root)")
map("n", "<leader>,", pick("buffers"), "Buffers")
map("n", "<leader>fb", pick("buffers"), "Buffers")
map("n", "<leader>/", pick("grep", "root"), "Grep (Root)")
map("n", "<leader>sg", pick("grep", "root"), "Grep (Root)")
map("n", "<leader>sG", pick("grep"), "Grep (cwd)")
map({ "n", "x" }, "<leader>sw", pick("grep_word", "root"), "Word or Selection (Root)")
map("n", "<leader>sb", pick("lines"), "Buffer Lines")
map("n", "<leader>sh", pick("help"), "Help Pages")
map("n", "<leader>sk", pick("keymaps"), "Keymaps")
map("n", "<leader>sc", pick("command_history"), "Command History")
map("n", "<leader>:", pick("command_history"), "Command History")
map("n", "<leader>ss", pick("lsp_symbols"), "LSP Symbols")
map("n", "<leader>sS", pick("lsp_workspace_symbols"), "LSP Workspace Symbols")
map("n", "<leader>sd", pick("diagnostics"), "Diagnostics")
map("n", "<leader>sD", pick("diagnostics_buffer"), "Buffer Diagnostics")
map("n", "<leader>st", pick("todo_comments"), "Todo Comments")
map("n", "<leader>su", function()
  Snacks.picker.undo()
end, "Undo History")
map("n", "<leader>e", function()
  Snacks.explorer({ cwd = root() })
end, "Explorer (Root)")
map("n", "<leader>E", function()
  Snacks.explorer()
end, "Explorer (cwd)")
map("n", "<leader>fe", function()
  Snacks.explorer({ cwd = root() })
end, "Explorer (Root)")
map("n", "<leader>fE", function()
  Snacks.explorer()
end, "Explorer (cwd)")
map({ "n", "x" }, "<leader>sr", function()
  require("grug-far").open({ transient = true })
end, "Search and Replace")

map("n", "<leader>gb", function()
  Snacks.git.blame_line()
end, "Git Blame Line")
map("n", "<leader>gB", pick("git_branches", "root"), "Git Branches")
map("n", "<leader>gl", pick("git_log", "root"), "Git Log")
map("n", "<leader>gL", pick("git_log_file", "root"), "Git Log File")
map("n", "<leader>gs", pick("git_status", "root"), "Git Status")
map("n", "<leader>gd", pick("git_diff", "root"), "Git Diff")
map("n", "]h", function()
  require("gitsigns").nav_hunk("next")
end, "Next Hunk")
map("n", "[h", function()
  require("gitsigns").nav_hunk("prev")
end, "Previous Hunk")
map({ "n", "x" }, "<leader>ghs", ":Gitsigns stage_hunk<CR>", "Stage Hunk")
map({ "n", "x" }, "<leader>ghr", ":Gitsigns reset_hunk<CR>", "Reset Hunk")
map("n", "<leader>ghS", function()
  require("gitsigns").stage_buffer()
end, "Stage Buffer")
map("n", "<leader>ghR", function()
  require("gitsigns").reset_buffer()
end, "Reset Buffer")
map("n", "<leader>ghp", function()
  require("gitsigns").preview_hunk_inline()
end, "Preview Hunk")
map("n", "<leader>ghb", function()
  require("gitsigns").blame_line({ full = true })
end, "Blame Line")
map("n", "<leader>ghd", function()
  require("gitsigns").diffthis()
end, "Diff This")
map({ "o", "x" }, "ih", ":<C-U>Gitsigns select_hunk<CR>", "Select Hunk")

map({ "n", "x", "o" }, "s", function()
  require("flash").jump()
end, "Flash")
map({ "n", "x", "o" }, "S", function()
  require("flash").treesitter()
end, "Flash Treesitter")
map("o", "r", function()
  require("flash").remote()
end, "Remote Flash")
map({ "o", "x" }, "R", function()
  require("flash").treesitter_search()
end, "Treesitter Search")
map("n", "]t", function()
  require("todo-comments").jump_next()
end, "Next Todo")
map("n", "[t", function()
  require("todo-comments").jump_prev()
end, "Previous Todo")
map("n", "<leader>cf", function()
  require("conform").format({ async = true })
end, "Format Buffer")
map("x", "<leader>cf", function()
  require("conform").format({ async = true })
end, "Format Selection")
map("n", "<leader>cd", vim.diagnostic.open_float, "Line Diagnostics")
map("n", "]d", function()
  vim.diagnostic.jump({ count = 1, float = true })
end, "Next Diagnostic")
map("n", "[d", function()
  vim.diagnostic.jump({ count = -1, float = true })
end, "Previous Diagnostic")
map("n", "]e", function()
  vim.diagnostic.jump({ count = 1, severity = vim.diagnostic.severity.ERROR, float = true })
end, "Next Error")
map("n", "[e", function()
  vim.diagnostic.jump({ count = -1, severity = vim.diagnostic.severity.ERROR, float = true })
end, "Previous Error")
map("i", "<C-k>", vim.lsp.buf.signature_help, "Signature Help")
map("n", "<leader>xx", "<cmd>Trouble diagnostics toggle<cr>", "Diagnostics (Trouble)")
map("n", "<leader>xX", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", "Buffer Diagnostics (Trouble)")
map("n", "<leader>cs", "<cmd>Trouble symbols toggle<cr>", "Symbols (Trouble)")
map("n", "<leader>cS", "<cmd>Trouble lsp toggle<cr>", "LSP References (Trouble)")
map("n", "<leader>xL", "<cmd>Trouble loclist toggle<cr>", "Location List (Trouble)")
map("n", "<leader>xQ", "<cmd>Trouble qflist toggle<cr>", "Quickfix List (Trouble)")

for key, direction in pairs({ h = "left", j = "down", k = "up", l = "right" }) do
  map("n", "<C-" .. key .. ">", "<C-w>" .. key, "Go to " .. direction .. " Window")
end
map("n", "<C-Up>", "<cmd>resize +2<cr>", "Increase Window Height")
map("n", "<C-Down>", "<cmd>resize -2<cr>", "Decrease Window Height")
map("n", "<C-Left>", "<cmd>vertical resize -2<cr>", "Decrease Window Width")
map("n", "<C-Right>", "<cmd>vertical resize +2<cr>", "Increase Window Width")
map("n", "<leader>ww", "<C-w>p", "Other Window")
map("n", "<leader>wd", "<C-w>c", "Delete Window")
map("n", "<leader>w-", "<C-w>s", "Split Window Below")
map("n", "<leader>w|", "<C-w>v", "Split Window Right")
map("n", "<leader>-", "<C-w>s", "Split Window Below")
map("n", "<leader>|", "<C-w>v", "Split Window Right")
map("n", "H", "<cmd>BufferLineCyclePrev<cr>", "Previous Buffer")
map("n", "L", "<cmd>BufferLineCycleNext<cr>", "Next Buffer")
map("n", "[b", "<cmd>BufferLineCyclePrev<cr>", "Previous Buffer")
map("n", "]b", "<cmd>BufferLineCycleNext<cr>", "Next Buffer")
map("n", "<leader>bd", function()
  Snacks.bufdelete()
end, "Delete Buffer")
map("n", "<leader>bo", function()
  Snacks.bufdelete.other()
end, "Delete Other Buffers")
map("n", "<leader>bb", "<cmd>e #<cr>", "Other Buffer")
map("n", "<leader>fn", "<cmd>enew<cr>", "New File")
map({ "n", "i", "x", "s" }, "<C-s>", "<cmd>w<cr><esc>", "Save File")
map("n", "<leader>qq", "<cmd>qa<cr>", "Quit All")
map("n", "<leader>qs", function()
  require("persistence").load()
end, "Restore Session")
map("n", "<leader>qS", function()
  require("persistence").select()
end, "Select Session")
map("n", "<leader>ql", function()
  require("persistence").load({ last = true })
end, "Restore Last Session")
map("n", "<leader>qd", function()
  require("persistence").stop()
end, "Stop Saving Session")
map("n", "<leader><tab><tab>", "<cmd>tabnew<cr>", "New Tab")
map("n", "<leader><tab>d", "<cmd>tabclose<cr>", "Close Tab")
map("n", "<leader><tab>]", "<cmd>tabnext<cr>", "Next Tab")
map("n", "<leader><tab>[", "<cmd>tabprevious<cr>", "Previous Tab")
map("n", "<leader>ft", function()
  Snacks.terminal(nil, { cwd = root() })
end, "Terminal (Root)")
map("n", "<leader>fT", function()
  Snacks.terminal()
end, "Terminal (cwd)")
map({ "n", "t" }, "<C-/>", function()
  Snacks.terminal(nil, { cwd = root() })
end, "Toggle Terminal")
map("t", "<Esc><Esc>", "<C-\\><C-n>", "Enter Normal Mode")
map("n", "<Esc>", "<cmd>nohlsearch<cr>", "Clear Search Highlight")
map("x", "<", "<gv", "Indent Left")
map("x", ">", ">gv", "Indent Right")
map("n", "<leader>?", function()
  require("which-key").show({ global = false })
end, "Buffer Keymaps")
map("n", "<leader>un", function()
  Snacks.notifier.hide()
end, "Dismiss Notifications")
map("n", "<leader>sn", function()
  Snacks.notifier.show_history()
end, "Notification History")

Snacks.toggle.option("wrap", { name = "Wrap" }):map("<leader>uw")
Snacks.toggle.option("relativenumber", { name = "Relative Number" }):map("<leader>uL")
Snacks.toggle.diagnostics():map("<leader>ud")
Snacks.toggle.inlay_hints():map("<leader>uh")
Snacks.toggle.indent():map("<leader>ug")
Snacks.toggle({
  name = "Auto Format",
  get = function()
    return vim.g.autoformat
  end,
  set = function(value)
    vim.g.autoformat = value
  end,
}):map("<leader>uf")
Snacks.toggle({
  name = "Buffer Auto Format",
  get = function()
    return vim.b.autoformat ~= false
  end,
  set = function(value)
    vim.b.autoformat = value
  end,
}):map("<leader>uF")

local group = vim.api.nvim_create_augroup("NixvimBehavior", { clear = true })
vim.api.nvim_create_autocmd("TextYankPost", {
  group = group,
  callback = function()
    vim.hl.on_yank()
  end,
})
vim.api.nvim_create_autocmd("BufReadPost", {
  group = group,
  callback = function(event)
    local mark = vim.api.nvim_buf_get_mark(event.buf, '"')
    if
      mark[1] > 0
      and mark[1] <= vim.api.nvim_buf_line_count(event.buf)
      and vim.bo[event.buf].filetype ~= "gitcommit"
    then
      pcall(vim.api.nvim_win_set_cursor, 0, mark)
    end
  end,
})
