# .sops.yaml
keys:
  - &worker age12qrrnsljt8xh8lfwsydq65axvqevuypj367d6vt3mjhhtfzfr4ks39dfew
  - &fear age1ts6f23tehdmrtzz03pxtgezg4tl4q0d0k6zx83emkc7g4xffldzqwdxn89

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age:
          - *worker
          - *fear
