name: Flake builds

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  nixos:
    name: NixOS / ${{ matrix.host }}
    runs-on: ubuntu-24.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        host: [fear]
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build system closure
        env:
          HOST: ${{ matrix.host }}
        run: nix build --no-update-lock-file --no-link --print-build-logs ".#nixosConfigurations.${HOST}.config.system.build.toplevel"

  darwin:
    name: Darwin / fearful
    runs-on: macos-26
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Build system closure
        run: nix build --no-update-lock-file --no-link --print-build-logs '.#darwinConfigurations.fearful.system'
